/**
 * @file    bbSSParams.h
 * @brief 	BallPlate model / controller / observer parameter values.
 *
 * File is automatically generated by the MatLab script __startSimulation.m__
 * Contains all parameters necessary for the MCU program, namely: 
 * 
 *          ORDER   : system order
 *          BB_SS_F : transition matrix
 *          BB_SS_G : input gain matrix
 *          BB_SS_C : measurement matrix
 *          BB_SS_K : control feedback gain vector
 *          BB_SS_V : closed loop gain adjustment
 *          BB_SS_L : observer (or Kalman) gain vector
 *
 * @author 	I.Lienhardt
 * @date   	2014-12-14 23:03:41 orig
 *          2016-11-09 Mys observer gains from mys simulation
 *          2019-02-06 Mys controller & observer gains
 *
 * Observer 2nd Order:
 *   Closed-Loop Poles:  -3, -2.5
 *   Observer    Poles: -10, -20
 *
 * Observer 3rd Order:
 *   Closed-Loop Poles:  -6, -2.5, -6
 *   Observer    Poles: -10, -20,  -5
 *
 * Kalman Filter 3rd Order:
 *   Closed-Loop Poles                   : 
 *   Kalman Filter measurement covariance:
 *   Kalman Filter process covariance    :
 *
 *
 *  Modifications
 *  160905   mys  use ZiSo controller gains: Kp = -1.5, Kd = -1.5
 *  161109   mys  use mys Obs3 gains: 
 *  161111   mys  use controller gains: Kp = -1.5, Kd = -1.0
 *                for HITEC645-Servo on X-axis    Kd = -1.5 oszillates !
 *  171108   Chuong control. gains: Kp = -2.2, Kd = -0.7 almost instable
 *  171115   mys  controller gains: Kp = -1.5, Kd = -1.1
 *  190206   mys  controller gains: Kp = -6.0, Kd = -3.0
 *                for Modelcraft VS-11AMB servo
 */



#ifndef __BB_SS_PARAM__ 
#define __BB_SS_PARAM__ 


#ifdef _SYS_2ND_ORDER_OBS_ 

  #define ORDER 2
// ballplate model
  #define BB_SS_F     {{+1.000000e+00, +5.000000e-02}, \
                       {+0.000000e+00, +1.000000e+00}}
  #define BB_SS_G     {-1.103248e-03, -4.412993e-02}
  #define BB_SS_C     {+1.000000e+00, +0.000000e+00}
// state feedback controller
//#define BB_SS_K     {-1.50,         -1.00}            // 161111 for HITEC-645 servo in X
  #define BB_SS_K     {-6.00,         -3.00}            // 190206 mys for Modelcraft VS-11AMB servo
  #define BB_SS_V      -6.00                            // 190206 mys controller gains
// state observer
  #define BB_SS_L     {+1.0,          +5.0}             // mys  OBS2 gains from Matlab sim


#elif defined _SYS_3RD_ORDER_OBS_ 

  #define ORDER 3
// ballplate model
  #define BB_SS_F     {{+1.000000e+00, +5.000000e-02, -9.402380e-04}, \
                       {+0.000000e+00, +1.000000e+00, -3.472754e-02}, \
                       {+0.000000e+00, +0.000000e+00, +6.065307e-01}}
  #define BB_SS_G     {-1.630101e-04, -9.402380e-03, +3.934693e-01}
  #define BB_SS_C     {+1.000000e+00, +0.000000e+00, +0.000000e+00}
// state feedback controller
  #define BB_SS_K     {-6.00,         -3.00,         +0.0}    // 190206 mys for Modelcraft VS-11AMB servo
  #define BB_SS_V      -6.00                                  // 190206 mys controller gains
// state observer
  #define BB_SS_L     {+1.1,          +6.1,          -0.17 }  // mys  OBS3 gains from Matlab sim


#elif defined _SYS_3RD_ORDER_KF_ 

  #define ORDER 3

  #define BB_SS_F     {{+1.000000e+00, +5.000000e-02, -9.402380e-04}, \
                       {+0.000000e+00, +1.000000e+00, -3.472754e-02}, \
                       {+0.000000e+00, +0.000000e+00, +6.065307e-01}}
  #define BB_SS_G     {-1.630101e-04, -9.402380e-03, +3.934693e-01}
  #define BB_SS_C     {+1.000000e+00, +0.000000e+00, +0.000000e+00}
  #define BB_SS_K     {-6.00,         -3.00,         +0.0}
  #define BB_SS_V      -6.00
  #define BB_SS_L     {+1.1,          +6.1,          -0.17}
	
#elif defined _SYS_4TH_ORDER_EKF_
	
	#define ORDER 4
	
	#define BB_SS_F     {{000000e+00, 00000e-02, 02380e-04, 0},{+0.000000e+00, 000000e+00, 0, 0},{+0.000000e+00, +0.000000e+00,0, 0},{0,0,0,0}}
                       
                       
  #define BB_SS_G     {-0, -0, +0,0}
  #define BB_SS_C     {+1.000000e+00, +0.000000e+00, +0.000000e+00, 0}
  #define BB_SS_K     {-6.00,         -3.00,         -0.5, -0.5} // state feedback controller gain vector
  #define BB_SS_V      -5.00
  //#define BB_SS_L     {+1.1,          +6.1,          -0.17,   	0}
	//#define BB_SS_Q		{ +5.25e-07, 	1.05e-4,    2, +0.001} //ms added Process noise covariance matrix
                       
     #define BB_SS_Q	    {2.0,50,1,0.005 }             
	//#define BB_SS_R {1.05e-6}
	#define BB_SS_R {2}
#else
  #undef ORDER
  #error "Define one of '_SYS_2ND_ORDER_OBS_', '_SYS_3RD_ORDER_OBS_' or '_SYS_3RD_ORDER_KF_' !"
#endif

#endif

